config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "employees#index"

  resource :employees do
    match '/:id' => 'employees#update_department_page', via: :get, :as => 'update_department_page'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
    belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_one :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    def index
       @employees = Employee.all 
    end

    def update_department_page
        @employee = Employee.find_by_id(params[:id])
        respond_to do |format| 
            format.html { render '_edit_dept_modal' }
        end
    end

    def update
      @employee = Employee.find_by_id(params[:employee][:id])
      @employee.department.update(name: params[:employee][:department])
      redirect_to root_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_edit_dept_modal.html.erb
<div class="modal-header">
  <h2 class="modal-title"><%= @employee.first_name %></h2>
</div>
<div class="modal-body">
  <%= form_with(model: @employee, url: employees_path, method: :put) do |form| %>
    <%= form.hidden_field :_method, value: "put" %>
    <label>Department:</label>
    <% departments = ["Product", "Sales", "Marketing", "Infra"] %>
    <%= form.select :department, options_for_select(departments, @employee.department&.name), { prompt: "Select department" }, { class: "form-select" } %>
    <br>
    <%= form.hidden_field :id, value: @employee.id %>

    <%= form.submit "Submit", class: "btn btn-primary text-center" %>
  <% end %>
</div>

app/views/employees/index.html.erb
<div class="container">
<div class="container mt-6">
<strong><h2 class="text-center">Employee List</h2></strong>
<table class="table">
<thead>
  <tr>
    <th scope="col">First Name</th>
    <th scope="col">Last Name</th>
    <th scope="col">Email</th>
    <th scope="col">Phone</th>
    <th scope="col">Salary</th>
    <th scope="col">Department</th>
    <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @employees.each do |employee|%>
    <tr>
      <th scope="row"><%= employee.first_name%></th>
      <td><%= employee.last_name%></td>
      <td><%= employee.email%></td>
      <td><%= employee.phone%></td>
      <td><%= employee.salary%></td>
      <td><%= employee.department.name%></td>
      <td class="text-primary"><%= link_to 'Edit Department', update_department_page_employees_path(employee.id), {:remote=>true,'data-toggle': 'modal', 'data-target': '#modal-window'} %></td>
    </tr>
  <%end%>
  </tbody>
</table>
</div>
</div>


<div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
  </div>
</div>
</div>

app/views/employees/update_department_page.js.erb
$("#modal-window").find(".modal-content").html("<%= j render(partial: 'employees/edit_dept_modal', locals: { id: @employee.id, name: [@employee.first_name, @employee.last_name].join(' ') }) %>");
$("#modal-window").modal();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>